
export const articles = [
  {
    id: 0,
    title: "Mira 101",
    description: "An essential guide to understanding the fundamentals of the MIRA ecosystem.",
    category: "Introduction",
    color: "purple",
    href: "https://x.com/shlokafc/status/1937843275614007331",
    image: "/mira101.png",
  },
  {
    id: 1,
    title: "Decoding Mira: An Annotated Journey Through the AI Verification Revolution",
    description: "The Day AI Broke Trust. A respected New York lawyer submits a legal brief to federal court.",
    category: "Category",
    color: "blue",
    href: "/articles/technical",
    image: "/decoding.png",
  },
  {
    id: 2,
    title: "How Delphi Oracle Transformed Crypto Research Accessibility with Mira's AI Technology",
    description: "The Research Paradox Delphi's research reports are legendary in crypto circles",
    category: "Category",
    color: "blue",
    href: "/articles/technical",
    image: "/article.png",
  },
  {
    id: 3,
    title: "How Mira's Verification Technology Revolutionized Learnrite's Educational Testing Platform",
    description: "Across Asia, millions of students know the feeling all too well: sleepless nights, endless cups of coffee, and the crushing weight of exams that will determine their entire future. ",
    category: "Category",
    color: "pink",
    href: "https://x.com/Mira_Network/status/1928096779746300355",
    image: "/article7.png",
  },
  {
    id: 4,
    title: "What If AI Could Prove Itself? @Mira_Network Network Already Does.",
    description: "We live in a time where most of the content we consume online is ai generated. But here’s the real question:",
    color: "pink",
    href: "https://x.com/Seymirel/status/1943977176434458738",
    image: "/4article.jpg",
  },
];  